version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redarky_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  go_scraper:
    build: ./scraper
    ports:
      - "8081:8081"

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/redarky_db
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  worker:
    build: ./api
    command: celery -A app.workers.celery_app.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/redarky_db
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

  flower:
    build: ./api
    command: celery -A app.workers.celery_app.celery flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - worker

  airflow-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow_password
      POSTGRES_DB: airflow_db
    ports:
      - "5433:5432" # Changed to 5433 so it doesn't conflict with your local Postgres on 5432

  airflow-init:
    image: apache/airflow:2.10.5-python3.11 # Upgraded for better stability
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow_password@airflow-db:5432/airflow_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./airflow:/opt/airflow
    depends_on:
      - airflow-db
    command: >
      bash -c "airflow db init && 
      airflow users create --username admin --firstname Hemant --lastname Sharma --role Admin --email admin@redarky.com --password admin"

  airflow-webserver:
    image: apache/airflow:2.10.5-python3.11
    restart: always
    depends_on:
      airflow-db:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    volumes:
      - ./airflow:/opt/airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow_password@airflow-db:5432/airflow_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.10.5-python3.11
    restart: always
    depends_on:
      airflow-db:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
    volumes:
      - ./airflow:/opt/airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow_password@airflow-db:5432/airflow_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    command: scheduler
