"""Added: AI Agent tables, Mission table update

Revision ID: 2160cc4e5888
Revises: 08d8bcdcf3b9
Create Date: 2026-04-27 17:19:22.389819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2160cc4e5888'
down_revision: Union[str, Sequence[str], None] = '08d8bcdcf3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('reddit_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reddit_username', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reddit_username', name='uq_reddit_credentials_user_username')
    )
    op.create_index(op.f('ix_reddit_credentials_user_id'), 'reddit_credentials', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_id'), 'agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_mission_id'), 'agent_runs', ['mission_id'], unique=False)
    op.create_table('market_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_gaps_mission_id'), 'market_gaps', ['mission_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_mission_id'), 'reports', ['mission_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_item_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_item_id'], ['data_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_item_id', name='uq_embeddings_data_item')
    )
    op.create_index(op.f('ix_embeddings_data_item_id'), 'embeddings', ['data_item_id'], unique=False)
    op.create_table('engagement_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_actions_report_id'), 'engagement_actions', ['report_id'], unique=False)
    op.add_column('data_items', sa.Column('dedup_hash', sa.String(length=64), nullable=False))
    op.alter_column('data_items', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data_items', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('data_items', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('data_items', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('data_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_data_items_dedup_hash'), 'data_items', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_data_items_mission_id'), 'data_items', ['mission_id'], unique=False)
    op.create_unique_constraint('uq_data_items_mission_hash', 'data_items', ['mission_id', 'dedup_hash'])
    op.create_foreign_key(None, 'data_items', 'missions', ['mission_id'], ['id'], ondelete='CASCADE')
    op.add_column('missions', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('missions', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('missions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('missions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('missions', 'goal',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_missions_owner_id'), 'missions', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'missions', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'missions', type_='foreignkey')
    op.drop_index(op.f('ix_missions_owner_id'), table_name='missions')
    op.alter_column('missions', 'goal',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('missions', 'updated_at')
    op.drop_column('missions', 'created_at')
    op.drop_column('missions', 'status')
    op.drop_column('missions', 'owner_id')
    op.drop_constraint(None, 'data_items', type_='foreignkey')
    op.drop_constraint('uq_data_items_mission_hash', 'data_items', type_='unique')
    op.drop_index(op.f('ix_data_items_mission_id'), table_name='data_items')
    op.drop_index(op.f('ix_data_items_dedup_hash'), table_name='data_items')
    op.alter_column('data_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('data_items', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('data_items', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('data_items', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('data_items', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('data_items', 'dedup_hash')
    op.drop_index(op.f('ix_engagement_actions_report_id'), table_name='engagement_actions')
    op.drop_table('engagement_actions')
    op.drop_index(op.f('ix_embeddings_data_item_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_reports_mission_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_market_gaps_mission_id'), table_name='market_gaps')
    op.drop_table('market_gaps')
    op.drop_index(op.f('ix_agent_runs_mission_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_reddit_credentials_user_id'), table_name='reddit_credentials')
    op.drop_table('reddit_credentials')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('agents')
    # ### end Alembic commands ###
